version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.2
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:3.2
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres:
    image: quay.io/debezium/example-postgres:3.2
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  connect:
    image: quay.io/debezium/connect:3.2
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
     - pg_sub
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    volumes:
      - ./jdbc-connector/lib:/kafka/connect/jdbc
  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - 8080:8080
    volumes:
      - ./akhq-application.yml:/app/application.yml
  adminer:
    image: adminer:5.2.1
    ports:
      - 8099:8080
    links:
     - postgres
     - pg_sub
  pg_sub:
    image: postgres:15.0
    ports:
     - 5433:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres